[general]
import = ["./themes/themes/vscode.toml"]

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 12

[terminal]
shell = { program = "powershell.exe", args = ["-NoLogo"] }
